### ISSUE TITLE
python2 support for LZMA compressed files

### ISSUE THREAD

**Issue by cbosdo** [srossross/rpmfile#25]
When using on an rpm file using LZMA compression in python2, I am getting such an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/rpmfile/__init__.py", line 118, in getmembers
    g = self.data_file
  File "/usr/lib/python2.7/dist-packages/rpmfile/__init__.py", line 172, in data_file
    self._data_file = lzma.LZMAFile(fileobj)
TypeError: coercing to Unicode: need string or buffer, _SubFile found
```

The corresponding code is:

```python
rpm_file = '/tmp/obsmvn-nWOni1/asm3-3.3.1-lp151.2.1.noarch.rpm'
rpm = rpmfile.open(rpm_file)
rpm.getmembers()
```

The problem is that the [pyliblzma](https://launchpad.net/pyliblzma) available in debian repositories for python2 doesn't take an opened file object for LZMAFile, but a filename only. LZMAFile constructor accepting a file object is only in the lzma python3 module.

**Comment by pdxjohnny** [comment]
I looked into this, it turns out the pyliblzma project only takes a filepath, it won't take a file object (if I remember correctly, this was a few months ago). I don't think this is going to be possible. Is this still something you need? If so do you have time to submit a PR? If not I think we'll have to close this issue (In light of Python 2 EOL). Please let us know, thanks!

**Comment by cbosdo** [comment]
I worked around it, let's close it
